name = "foxrepstest"
# Das aktuelle Datum ist entscheidend für Cloudflare's Kompatibilität.
compatibility_date = "2025-11-29"

# Dieser Abschnitt ist alles, was du für eine statische Seite brauchst.
[assets]
directory = "."
